### ISSUE TITLE
Message: Errno::ENOENT: No such file or directory - vboxwebsrv -H 0.0.0.0 -b

### ISSUE THREAD

**Issue by mevam** [katosys/kato#52]
Message: Errno::ENOENT: No such file or directory - vboxwebsrv -H 0.0.0.0 -b
How to solve this problem?

**Comment by mevam** [comment]
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: <provider config: virtualbox>
Line number: /kato/Vagrantfile
Message: Errno::ENOENT: No such file or directory - vboxwebsrv -H 0.0.0.0 -b

**Comment by h0tbird** [comment]
Are you running on Linux or OSX?
The `vboxwebsrv` should be part of your VirtualBox installation.
In my Arch system it looks like this:

```
[0] ~ >> which vboxwebsrv         
/usr/sbin/vboxwebsrv
[0] ~ >> ll /usr/sbin/vboxwebsrv                    
lrwxrwxrwx 1 root root 4 Mar 16 22:03 /usr/sbin/vboxwebsrv -> VBox*
```

**Comment by mevam** [comment]
**Thank you, you are right, I reinstall the system, forget to add it to the environment variable.**

**Comment by mevam** [comment]
**Thank you, you are right, I reinstall the system, forget to add it to the environment variable**
